# -*- coding: utf-8 -*-
"""task3_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nWOOEZWJv0mgE29oxetYxSTk1132UQqP

### **Task 3 — Analysis with Pandas & NumPy**

# 1 — Load and Explore
"""

#Loading data_clean.csv into a Pandas DataFrame
import pandas as pd
cleaned_data=pd.read_csv("/content/data_clean.csv")

#first 5 rows
print(f"first 5 rows:\n\n {cleaned_data.head()}")

#shape of the DataFrame
print(f"loaded data: {cleaned_data.shape}")

#average score and average num_comments across all stories
print(f"average score : {round(cleaned_data["score"].mean(),2)}")
print(f"average comments: {round(cleaned_data["num_comments"].mean(),2)}")

"""# 2 — Basic Analysis with NumPy"""

#mean, median, and standard deviation,highest,lowest of score
print("---Numpy stats----")
print(f"Mean Score : {round(cleaned_data["score"].mean(),2)}")
print(f"Median Score : {cleaned_data["score"].median()}")
print(f"std deviation : {round(cleaned_data["score"].std(),2)}")
print(f"Max Score : {cleaned_data["score"].max()}")
print(f"Min Score : {cleaned_data["score"].min()}")

#most stories in category
max_value=cleaned_data["category"].value_counts().max()
max_category=cleaned_data["category"].value_counts().idxmax()
print(f"Most stories in : {max_category} ({max_value} stories)")

#most commented story
most_comm_titles=cleaned_data.loc[cleaned_data["num_comments"].idxmax(),"title"]
total_comments=cleaned_data.loc[cleaned_data["num_comments"].idxmax(),"num_comments"]
print(f"""most commented story : "{most_comm_titles}"--{total_comments} comments""")

"""## 3 — Add New Columns"""

#Adding engagement and is_popular two cloumns in to DataFrame
cleaned_data["engagement"]=round(cleaned_data["num_comments"]/(cleaned_data["score"]+1),2)
cleaned_data["is_popular"]=cleaned_data["score"].mean()< cleaned_data["score"]

"""## 4 — Save the Result"""

cleaned_data.to_csv("data_analysed.csv",index=False)