# -*- coding: utf-8 -*-
"""task4_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pl_syvKAeOfeGivxzu5xjml-ggknnhlo

### **Task 4 — Visualizations**
"""

import pandas as pd
import os
import matplotlib.pyplot as plt

"""## 1 — Setup"""

#Load data and setup
df_visualization=pd.read_csv("/content/data_analysed.csv")

#creating folder
if not os.path.exists("outputs"):
  os.makedirs("outputs")

#Filter top  stories
top10_stories=df_visualization.sort_values("title",ascending=False).head(10)

#shorten titles longer than  characters
def short_title(title,max_length=50):
  if len(title)>max_length:
    return title[:50]+"..."
  return title

top10_stories["title"]=top10_stories["title"].apply(short_title)

"""## 2 — Chart 1: Top 10 Stories by Score"""

# Horizontal bar chart showing the top 10 stories by score
plt.barh(y="title",width="score",data=top10_stories)
plt.xlabel("Score",fontsize=20)
plt.ylabel("Title",fontsize=20)
plt.title("Top 10 stories by score",fontsize=25)
plt.savefig("/content/outputs/top10_stories.png")
plt.show()

"""## 3 — Chart 2: Stories per Category"""

#counting category wise total stories
category_count=df_visualization["category"].value_counts()

#Bar chart showing how many stories come from each category
plt.bar(category_count.index,category_count.values,color=['red','blue','green','orange','cyan'])
plt.xlabel("category",fontsize=15)
plt.ylabel("title",fontsize=15)
plt.title("Stories by category",fontsize=20)
plt.savefig("/content/outputs/categories.png")
plt.show()

"""## 4 — Chart 3: Score vs Comments"""

#scatter plot showing relation between score and num_comments
plt.scatter(x="score",y="num_comments",data= df_visualization,c="is_popular",cmap="coolwarm")
plt.xlabel("Score",fontsize=15)
plt.ylabel("Num_comment",fontsize=15)
plt.title("Score vs Comments ",fontsize=20)
plt.savefig("/content/outputs/scatter.png")
plt.show()

#combining all 3 charts into one figure
fig,axes =plt.subplots(1,3,figsize=(15,5))
axes[0].barh(y="title",width="score",data=top10_stories)
axes[0].set_title("Top 10 stories by score")

axes[1].bar(category_count.index,category_count.values,color=['red','blue','green','orange','cyan'])
axes[1].set_title("Stories by category")
axes[1].set_xticklabels(category_count.index,rotation=45,ha="right")

axes[2].scatter(x="score",y="num_comments",data= df_visualization,c="is_popular",cmap="coolwarm")
axes[2].set_title("Score vs Comments ")

plt.suptitle("Trendpluse Dashboard")
plt.tight_layout()
plt.savefig("/content/outputs/dashboard.png")
plt.show()