# -*- coding: utf-8 -*-
"""task1_data_collection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lHwmuEVhXQj2VPI4_MoM5BWNVcpXp3G-

### **Task 1 — Fetch Data from API**
"""

import requests
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import time
from datetime import datetime
import json

url1="https://hacker-news.firebaseio.com/v0/topstories.json"
#fetching story IDs from given url
response=requests.get(url1)
#Assigning to ids variable
ids=response.json()

datas=[]
try:
  for id in ids:
    url2=f"https://hacker-news.firebaseio.com/v0/item/{id}.json"
    headers = {"User-Agent": "TrendPulse/1.0"}

    #fetching each story details from given URL
    response=requests.get(url2,headers=headers)
    response.raise_for_status()
    if response.status_code==200:
      datas.append(response.json())
    elif response.status_code==429:
      print("Too many requests")
    else:
      print(f"errors:{response.status_code}")
except requests.exceptions.ConnectionError:
  print("Failed to connect to server")
except requests.exceptions.HTTPError as e:
  print(f"http error:{e}")
except Exception as e:
  print(f"something went wrong: {e}")

#check whether all data has been pulled
if len(datas) == len(ids):
    print("All data fetched")
else:
    print("Still missing data")

all_data=[]
categories={
    "technology":["AI", "software", "tech", "code", "computer", "data", "cloud", "API", "GPU", "LLM"],
    "worldnews":["war", "government", "country", "president", "election", "climate", "attack", "global"],
    "sports":["NFL", "NBA", "FIFA", "sport", "game", "team", "player", "league", "championship"],
    "science":["research", "study", "space", "physics", "biology", "discovery", "NASA", "genome"],
    "entertainment":["movie", "film", "music", "Netflix", "game", "book", "show", "award", "streaming"]
}
#loop through each data in datas to add required fields category and current date and time in data
for data in datas:
  for category,keywords in categories.items():
    for keyword in keywords:
      if keyword.lower() in data["title"].lower():
        data["category"]= category
        data["collected_at"]=datetime.now().strftime("%d-%m-%y %H:%m:%s")
        all_data.append(data)

#collecting the data by category
categories_data={}
for category,keywords in categories.items():
  categories_data[category]=[]
  for data in all_data:
    cat=data["category"]
    if category==cat:
      categories_data[category].append(story)
  time.sleep(2)
print(categories_data)

#Extracting the required fields
stories=[]
for data in all_data:
  story_dict={}
  story_dict["post_id"]=data.get("id")
  story_dict["title"]=data.get("title")
  story_dict["category"]=data.get("category")
  story_dict["score"]=data.get("score")
  story_dict["num_commnets"]=data.get("descendants")
  story_dict["author"]=data.get("by")
  story_dict["collectde_at"]=data.get("collected_at")
  stories.append(story_dict)
print(stories)
print(f"total stories:{len(stories)}")

#saved the stories data into the file
with open("data_20260410.json","w")as f:
  json.dump(stories,f,indent=4)
  print(f"Collected {len(stories)} stories. Saved to data_20260410.json")

#total count of stories by category
category_count={}

for story in stories:
  cat=story["category"]
  if cat in category_count:
    category_count[cat]+=1
  else:
    category_count[cat]=1
print(category_count)