# -*- coding: utf-8 -*-
"""task1_data_collection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lHwmuEVhXQj2VPI4_MoM5BWNVcpXp3G-

### **Task 1 — Fetch Data from API**
"""

import requests
import time
from datetime import datetime
import json

def fetch_ids():
  url1="https://hacker-news.firebaseio.com/v0/topstories.json"
  #fetching story IDs from given url
  response=requests.get(url1)
  #Assigning to ids variable
  ids=response.json()[:500]
  return  ids

def fetch_stories(ids):
  collected_data=[]
  try:
    for id in ids:
      url2=f"https://hacker-news.firebaseio.com/v0/item/{id}.json"
      headers = {"User-Agent": "TrendPulse/1.0"}

      #fetching each story details from given URL
      response=requests.get(url2,headers=headers)
      response.raise_for_status()
      if response.status_code==200:
        collected_data.append(response.json())
      elif response.status_code==429:
        print("Too many requests")
        return None
      else:
        print(f"errors:{response.status_code}")
        return None
    return collected_data
  except requests.exceptions.ConnectionError:
    print("Failed to connect to server")
  except requests.exceptions.HTTPError as e:
    print(f"http error:{e}")
  except Exception as e:
    print(f"something went wrong: {e}")
collected_data=fetch_stories(fetch_ids())
#check whether all data has been pulled
if len(collected_data) == len(fetch_ids()):
    print("All data fetched")
else:
    print("Still missing data")

#Categorizing the data using keywords
categories={
    "technology":["AI", "software", "tech", "code", "computer", "data", "cloud", "API", "GPU", "LLM"],
    "worldnews":["war", "government", "country", "president", "election", "climate", "attack", "global"],
    "sports":["NFL", "NBA", "FIFA", "sport", "game", "team", "player", "league", "championship"],
    "science":["research", "study", "space", "physics", "biology", "discovery", "NASA", "genome"],
    "entertainment":["movie", "film", "music", "Netflix", "game", "book", "show", "award", "streaming"]
}
#loop through each data in datas to add required fields category and current date and time in data
def categories_data(categories,collected_data):
  categories_data=[]
  for data in collected_data:
    for category,keywords in categories.items():
      for keyword in keywords:
        if keyword.lower() in data["title"].lower():
          data["category"]= category
          data["collected_at"]=datetime.now().strftime("%d-%m-%y %H:%m:%s")
          categories_data.append(data)
  return categories_data
categories_data=categories_data(categories,collected_data)

#Extracting the required fields
def required_stories(all_data,categories):
  stories=[]
  categories_count={cats:0 for cats in categories}
  for category,keywords in categories.items():
    for data in all_data:
      cat=data.get("category","")
      if category==cat:
        categories_count[category]+=1
        if categories_count[category]<25:
          story_dict={}
          story_dict["post_id"]=data.get("id")
          story_dict["title"]=data.get("title")
          story_dict["category"]=data.get("category")
          story_dict["score"]=data.get("score")
          story_dict["num_comments"]=data.get("descendants")
          story_dict["author"]=data.get("by")
          story_dict["collectde_at"]=data.get("collected_at")
          stories.append(story_dict)
  return stories
stories= required_stories(categories_data,categories)
print(f"total stories:{len(stories)}")

#total count of stories by category
category_total={}

for story in stories:
  cat=story["category"]
  if cat in category_total:
    category_total[cat]+=1
  else:
    category_total[cat]=1
print(category_total)

#saved the stories data into the file
with open("data_20260410.json","w")as f:
  json.dump(stories,f,indent=4)
  print(f"Collected {len(stories)} stories. Saved to data_20260410.json")