# -*- coding: utf-8 -*-
"""task2_data_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tusI3lXwDarmxpktuFkzVDpk4Fwphz1R

### **Task 2 — Clean the Data & Save as CSV**
"""

#Loaded the json file from folder(data_20260410.json) into  a DataFrame
import pandas as pd
import json
with open("/content/data_20260410.json","r") as f:
  stories=json.load(f)
stories_data=pd.DataFrame(stories)

#total rows loaded into a datafrme
print(f"Loaded {stories_data.shape[0]} from data_20260410.json")

#removing rows with the same post_id
stories_data=stories_data.drop_duplicates(subset="post_id")
print(f"after removing duplicates: {stories_data.shape[0]}")

# droping rows where post_id, title, or score is missing

stories_data=stories_data.dropna(subset=["post_id","title","score"])
print(f"After removing nulls: {stories_data.shape[0]}")

#make sure score and num_comments are integers.

stories_data["score"]=pd.to_numeric(stories_data["score"],errors="coerce").astype("Int64")
stories_data["num_comments"]=pd.to_numeric(stories_data["num_comments"],errors="coerce").astype("Int64")

#removing stories where score is less than 5
stories_data=stories_data[stories_data["score"]>5]
print(f"After removing low scores : {stories_data.shape[0]}")

#striping extra spaces from the title column
stories_data["title"]=stories_data["title"].str.strip()

#Save the cleaned DataFrame to data/trends_clean.csv
stories_data.to_csv("data_clean.csv",index=False)
print(f"saved {stories_data.shape[0]} rows to data_clean.csv")

#total count of stories by category
print("Stories per category:")
stories_data["category"].value_counts()